const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Gritsenko_Spine,
		C3.Plugins.Browser,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Gritsenko_Spine.Cnds.OnSkeletonLoaded,
		C3.Plugins.Gritsenko_Spine.Acts.SetSize,
		C3.Plugins.Gritsenko_Spine.Exps.TextureWidth,
		C3.Plugins.Gritsenko_Spine.Exps.TextureHeight,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Gritsenko_Spine.Exps.Animations,
		C3.Plugins.Gritsenko_Spine.Exps.Skins,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Gritsenko_Spine.Acts.ZMoveToObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Gritsenko_Spine.Cnds.IsAnimationPlaying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Gritsenko_Spine.Acts.SetAnimation,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Gritsenko_Spine.Cnds.OnAnimationFinished,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Gritsenko_Spine.Acts.Flip,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Gritsenko_Spine.Acts.SetAnimationSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Gritsenko_Spine.Cnds.OnEvent,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Gritsenko_Spine.Cnds.PickParent,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{speedRoll: 0},
	{pukul: 0},
	{terpukul: 0},
	{HP: 0},
	{HPmax: 0},
	{combo: 0},
	{memukul: 0},
	{Platform: 0},
	{Tween: 0},
	{Timer: 0},
	{DragDrop: 0},
	{OBJ_Player: 0},
	{Touch: 0},
	{Keyboard: 0},
	{OBJ_SpinePlayer: 0},
	{Browser: 0},
	{TB_BG: 0},
	{ScrollTo: 0},
	{OBJ_Cam: 0},
	{OBJ_Obstacle: 0},
	{BTN_Left: 0},
	{BTN_Right: 0},
	{BTN_Jump: 0},
	{BTN_Roll: 0},
	{BTN_Hit: 0},
	{H_BottomLeft: 0},
	{H_BottomRight: 0},
	{BTN_VirtualButton: 0},
	{H_TopRight: 0},
	{wall: 0},
	{barHp: 0},
	{H_TopLeft: 0},
	{maxWidth: 0},
	{TB_HP: 0},
	{OBJ_SpineEnemy: 0},
	{mengejar: 0},
	{kesulitan: 0},
	{OBJ_Enemy: 0},
	{Sine: 0},
	{OBJ_Finish: 0},
	{UI_Transition: 0},
	{TXT_Level: 0},
	{OBJ_PlayerCollision: 0},
	{OBJ_EnemyCollision: 0},
	{OBJ_Mine: 0},
	{Bullet: 0},
	{OBJ_OverheadTrap: 0},
	{Fam_Button: 0},
	{menang: 0},
	{virtualButton: 0},
	{level: 0},
	{efek: 0}
];

self.InstanceType = {
	Solid: class extends self.ISpriteInstance {},
	OBJ_Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	OBJ_SpinePlayer: class extends self.IWorldInstance {},
	Browser: class extends self.IInstance {},
	TB_BG: class extends self.ITiledBackgroundInstance {},
	OBJ_Cam: class extends self.ISpriteInstance {},
	OBJ_Obstacle: class extends self.ITiledBackgroundInstance {},
	BTN_Left: class extends self.ISpriteInstance {},
	BTN_Right: class extends self.ISpriteInstance {},
	BTN_Jump: class extends self.ISpriteInstance {},
	BTN_Roll: class extends self.ISpriteInstance {},
	BTN_Hit: class extends self.ISpriteInstance {},
	H_BottomLeft: class extends self.ISpriteInstance {},
	H_BottomRight: class extends self.ISpriteInstance {},
	BTN_VirtualButton: class extends self.ISpriteInstance {},
	H_TopRight: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	barHp: class extends self.ISpriteInstance {},
	H_TopLeft: class extends self.ISpriteInstance {},
	TB_HP: class extends self.ITiledBackgroundInstance {},
	OBJ_SpineEnemy: class extends self.IWorldInstance {},
	OBJ_Enemy: class extends self.ISpriteInstance {},
	OBJ_Finish: class extends self.ISpriteInstance {},
	UI_Transition: class extends self.ISpriteInstance {},
	TXT_Level: class extends self.ITextInstance {},
	OBJ_PlayerCollision: class extends self.ISpriteInstance {},
	OBJ_EnemyCollision: class extends self.ISpriteInstance {},
	OBJ_Mine: class extends self.ISpriteInstance {},
	OBJ_OverheadTrap: class extends self.ISpriteInstance {},
	Fam_Button: class extends self.ISpriteInstance {}
}